#!/bin/bash

JSON_PATH=""
TEST=""

NARGS=$(($#-1))

for (( iarg=1; iarg<=NARGS; iarg++)); do
    jarg=$((iarg+1))

    if [ "${!iarg}" == "--json" ]
        then
            JSON_PATH=${!jarg}
    fi
    if [ "${!iarg}" == "--test" ]
        then
            TEST=${!jarg}
    fi
done

TORUN="python3 $( dirname -- $0; )/main.py"

if [ "${JSON_PATH}" == "" ]; then
    echo "Parameter is missing:"
    echo "--json: path of the required metadata JSON file"
else
    TORUN="${TORUN} --json=${JSON_PATH}"
fi

if [ "${TEST}" != "" ]; then
    TORUN="${TORUN} --test=${TEST}"
fi

$TORUN